Sunina Thapa


Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

array = np.zeros((2, 2))
print(array)


[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [ ]:
array = np.ones((4, 2))
print(array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
shape = (3, 3)
fill_value = 7
dtype = int

array = np.full(shape, fill_value, dtype=dtype)
print(array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
given_array = np.array([[4, 5, 6], [7, 8, 9]])

zero_array = np.zeros_like(given_array)
print(zero_array)


[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
given_array = np.array([[2,3,4], [5,6,7]])
one_array = np.ones_like(given_array)
print(one_array)


[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

#an array with values from 10 to 49
array = np.arange(10, 49)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
import numpy as np

# 3x3 matrix with values from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


 3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

#a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

random_array = np.random.random(30)
mean_of_array = random_array.mean()
print(mean_of_array)


0.41610318322566575


 5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

random_array = np.random.random(100).reshape((10,10))
max_of_array = random_array.max()
min_of_array = random_array.min()
print(random_array)
print(max_of_array)
print(min_of_array)


[[0.09569609 0.24963979 0.06979898 0.04649845 0.19990304 0.78600196
  0.1687861  0.75111106 0.88527761 0.40724141]
 [0.7776883  0.63617023 0.70924225 0.81055084 0.17147907 0.78757446
  0.87918185 0.16822377 0.96223288 0.59854674]
 [0.74587055 0.95368152 0.47574858 0.29215756 0.1561531  0.11776143
  0.95371876 0.17253992 0.66750128 0.80849859]
 [0.07016224 0.37364007 0.85519281 0.36868746 0.09652593 0.72891519
  0.62949758 0.15990284 0.11732166 0.50743059]
 [0.35383617 0.24821475 0.61782379 0.64823043 0.15191466 0.20471284
  0.73250043 0.19619833 0.29406861 0.06654185]
 [0.89160087 0.84986556 0.11854706 0.85120242 0.79129302 0.7448937
  0.72856687 0.37862679 0.80174595 0.67232163]
 [0.92890169 0.03298695 0.01854677 0.3102064  0.68896386 0.03359486
  0.07766016 0.54084466 0.52166538 0.15109678]
 [0.51146752 0.67028161 0.55096014 0.44541187 0.51664556 0.18894021
  0.05272137 0.10387937 0.77662549 0.23696798]
 [0.34634915 0.97887167 0.52984197 0.5234161  0.75424653 0.64986288
  0.03732002 

 6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

#a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element with 1
zero_array[4] = 1

print("Modified Array:", zero_array)

Modified Array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

 #given arr
arr = np.array([1, 2, 0, 0, 4, 0])

# Reversing the array
reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)


Original Array: [1 2 0 0 4 0]
Reversed Array: [0 4 0 0 2 1]


 8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

rows, cols = 5, 5
# Creating 2d array with 1
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print("2D Array with Border of 1 and Inside 0:\n", array)


2D Array with Border of 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard[1::2, 1::2] = 0
print(checkerboard)



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x + y

print("Array x:\n", x)
print("Array y:\n", y)
print("Sum of x and y:\n", result)


Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Sum of x and y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x - y

print("Array x:\n", x)
print("Array y:\n", y)
print("Difference of x and y:\n", result)


Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])

result = x * 3

print("Array x:\n", x)
print("Array x multiplied by 3:\n", result)


Array x:
 [[1 2]
 [3 5]]
Array x multiplied by 3:
 [[ 3  6]
 [ 9 15]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)


Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Concatenate x and y along the row
xy_concatenated = np.concatenate((x, y), axis=0)

# Concatenate v and w along the column
vw_concatenated = np.column_stack((v, w))

print("Concatenated x and y along row:")
print(xy_concatenated)

print("\nConcatenated v and w along column:")
print(vw_concatenated)


Concatenated x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along column:
[[ 9 11]
 [10 12]]


 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Attempt to concatenate x and v along rows (axis=0)
try:
    result = np.concatenate((x, v), axis=0)
    print("Concatenated x and v along row:")
    print(result)
except ValueError as e:
    print(f"Error: {e}")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


When using np.concatenate, the arrays must have the same dimensions along all axes except the axis being concatenated. Here, x has two dimensions, but v has only one, so their shapes are incompatible for concatenation.

 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A and A_inv
result = np.dot(A, A_inv)

# Identity matrix (2x2)
I = np.eye(2)

# Check result
print("A * A^-1:")
print(result)
print("\nIs A * A^-1 equal to I?", np.allclose(result, I))


A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^-1 equal to I? True


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print and compare
print("AB:")
print(AB)
print("\nBA:")
print(BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))


AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False


In [ ]:
# Compute (AB)^T
AB_transpose = np.dot(A, B).T

# Compute B^T * A^T
BT_AT = np.dot(B.T, A.T)

# Print and compare
print("(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T:")
print(BT_AT)
print("\nIs (AB)^T equal to B^T * A^T?", np.allclose(AB_transpose, BT_AT))


(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True


• Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9

In [ ]:
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the solution
print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]
